### ISSUE TITLE
Link do docs broken in readme.md

### ISSUE THREAD

**Issue by stoldtjo** [FZJ-IEK3-VSA/ETHOS_PeNALPS#2]
The link on the readme.md starting page of the project is broken and clicking it will cause the user to be referred to a 404 error page.

**Comment by stoldtjo** [comment]
Links in section [Working Principle](https://github.com/FZJ-IEK3-VSA/ETHOS_PeNALPS/tree/main?tab=readme-ov-file#working-principle) are also broken.

**Comment by julian-belina** [comment]
Thank you for pointing out the bug. It has been fixed.

**Comment by stoldtjo** [comment]
Hi, there are still errors. See links in following sentences, both of which yield 404.

> A further description of the model definition can be found [here](https://github.com/FZJ-IEK3-VSA/ETHOS_PeNALPS/blob/main/%5Bethos_penalps_articles/model_description.md%5D(https:/ethospenalps.readthedocs.io/en/latest/ethos_penalps_articles/model_description.html)).

> A ReadTheDocs Documentation can be found [here](https://ethospenalps.readthedocs.io/en/latest/Introduction.html).

**Comment by julian-belina** [comment]
Thank you for rechecking. All links in the Readme should work as expected now.

**Comment by stoldtjo** [comment]
I see this link is failing:

`The [HTML documentation provides a tutorial](https://ethospenalps.readthedocs.io/en/latest/ethos_penalps_tutorial/overview.html)`

**Comment by julian-belina** [comment]
Thank you for reporting the bug. It has been fixed in 1.0.5

**Comment by stoldtjo** [comment]
Still looks broken to me...

**Comment by julian-belina** [comment]
Sorry, for the inconvenience...

To overcome the problematic of dead links, I started to use [linkcheckmd](https://pypi.org/project/linkcheckmd/) for the Readme.md and 

`
jupyter-book build documentation/ --builder linkcheck 
`
for the documentation. All links should work as expected now.
